# Generated by Django 5.2.7 on 2025-10-24 11:58

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaarmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=accounts.fields.EncryptedTextField(),
        ),
    ]
